# Generated by Django 6.0.2 on 2026-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_alter_sale_sold_at_saleexpensesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emoji',
            field=models.CharField(default='🧁', max_length=10),
        ),
    ]
